// Generated by CoffeeScript 1.3.3
(function() {
  var abspath, globalRequire, modules;

  modules = {};

  abspath = function(fromName, pathName) {
    var base, baseName, path;
    baseName = fromName.split('/');
    baseName.pop();
    baseName = baseName.join('/');
    if (pathName[0] === '/') {
      return pathName;
    } else {
      path = pathName.split('/');
      if (baseName === '/') {
        base = [''];
      } else {
        base = baseName.split('/');
      }
      while (base.length > 0 && path.length > 0 && path[0] === '..') {
        base.pop();
        path.shift();
      }
      if (base.length === 0 || path.length === 0 || base[0] !== '') {
        throw "Invalid path: " + (base.join('/')) + "/" + (path.join('/'));
      }
      return "" + (base.join('/')) + "/" + (path.join('/'));
    }
  };

  window.define = function(moduleName, closure) {
    return modules[moduleName] = {
      closure: closure,
      instance: null
    };
  };

  window.require = globalRequire = function(moduleName) {
    var exports, module, moduleRequire;
    module = modules[moduleName];
    if (module === void 0) {
      throw 'Module not found: ' + moduleName;
    }
    if (module.instance === null) {
      moduleRequire = function(requirePath) {
        var path;
        path = abspath(moduleName, requirePath);
        return globalRequire(path);
      };
      exports = {};
      exports = module.closure(exports, moduleRequire);
      module.instance = exports;
    }
    return module.instance;
  };

}).call(this);
